import "@ai-colab-platform/core/globals.css";
import type { Metadata } from "next";
import { RootLayout as SharedRoot } from "@repo/rootlayout-config";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <SharedRoot banner="DEBUG: Welcome to docs!">{children}</SharedRoot>;
}
